blank_issues_enabled: false
contact_links:
  - name: BlitzPy Discussions
    url: https://github.com/yourusername/blitzpy/discussions
    about: Please ask and answer questions here.
  - name: BlitzPy Documentation
    url: https://github.com/yourusername/blitzpy
    about: Check the documentation before reporting issues. 